### ISSUE TITLE
Finalise training defaults and options

### ISSUE THREAD

**Issue by dsmurrell** [cambDI/camb_old#13]

**Comment by isidroc** [comment]
To allow proper tunning in GetCVTrainControl, all the arguments of trControl should be also arguments of GetCVTrainControl with reasonable default values.
Thus, the amateur user can run it without further problems, but allowing also flexibility for experienced ones.
For instance, this needs to be tunable in order to allow ensemble modeling:
set.seed(1)
folds=5
repeats=1
trControl <- trainControl(method='cv', number=folds, repeats=repeats, returnResamp='none',
                          returnData=FALSE, savePredictions=TRUE,
                          verboseIter=TRUE, allowParallel=TRUE,
                          index=createMultiFolds(y.train, k=folds, times=repeats))
